/**
 * Error Classification — canonical error codes for the ITMS runtime.
 *
 * Every observable failure emitted by the application must belong to one
 * of these classes. Never emit a generic "error" — always classify.
 *
 * Used in structured logs as: { errorClass: ErrorClass.GPS_INVALID }
 */

export const ErrorClass = {
  // Authentication & Authorization
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_ROLE_DENIED: 'AUTH_ROLE_DENIED',
  AUTH_ADMIN_UNAVAILABLE: 'AUTH_ADMIN_UNAVAILABLE',

  // GPS Pipeline
  GPS_INVALID_COORDINATES: 'GPS_INVALID_COORDINATES',
  GPS_NULL_ISLAND: 'GPS_NULL_ISLAND',
  GPS_OUT_OF_ORDER: 'GPS_OUT_OF_ORDER',
  GPS_JUMP_TOO_LARGE: 'GPS_JUMP_TOO_LARGE',
  GPS_SPEED_EXCEEDED: 'GPS_SPEED_EXCEEDED',
  GPS_NO_ACTIVE_TRIP: 'GPS_NO_ACTIVE_TRIP',
  GPS_PERSIST_FAILED: 'GPS_PERSIST_FAILED',
  GPS_DUPLICATE_TIMESTAMP: 'GPS_DUPLICATE_TIMESTAMP',

  // Trip Management
  TRIP_LOCK_CONFLICT: 'TRIP_LOCK_CONFLICT',
  TRIP_LOCK_FAILED: 'TRIP_LOCK_FAILED',
  TRIP_VALIDATION_FAILED: 'TRIP_VALIDATION_FAILED',
  TRIP_NOT_FOUND: 'TRIP_NOT_FOUND',
  TRIP_OWNERSHIP_DENIED: 'TRIP_OWNERSHIP_DENIED',
  TRIP_HEARTBEAT_FAILED: 'TRIP_HEARTBEAT_FAILED',

  // Database
  DATABASE_QUERY_FAILED: 'DATABASE_QUERY_FAILED',
  DATABASE_RPC_FAILED: 'DATABASE_RPC_FAILED',
  DATABASE_CONSTRAINT_VIOLATION: 'DATABASE_CONSTRAINT_VIOLATION',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',

  // Notifications
  NOTIFICATION_FCM_FAILED: 'NOTIFICATION_FCM_FAILED',
  NOTIFICATION_ALREADY_SENT: 'NOTIFICATION_ALREADY_SENT',
  NOTIFICATION_LOCK_FAILED: 'NOTIFICATION_LOCK_FAILED',
  NOTIFICATION_UNAVAILABLE: 'NOTIFICATION_UNAVAILABLE',

  // WebSocket
  WEBSOCKET_AUTH_FAILED: 'WEBSOCKET_AUTH_FAILED',
  WEBSOCKET_RATE_LIMITED: 'WEBSOCKET_RATE_LIMITED',
  WEBSOCKET_INVALID_MESSAGE: 'WEBSOCKET_INVALID_MESSAGE',
  WEBSOCKET_REPLAY_DETECTED: 'WEBSOCKET_REPLAY_DETECTED',
  WEBSOCKET_HEARTBEAT_TIMEOUT: 'WEBSOCKET_HEARTBEAT_TIMEOUT',
  WEBSOCKET_QUEUE_OVERFLOW: 'WEBSOCKET_QUEUE_OVERFLOW',
  WEBSOCKET_HANDLER_ERROR: 'WEBSOCKET_HANDLER_ERROR',
  WEBSOCKET_SEND_FAILED: 'WEBSOCKET_SEND_FAILED',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_PAYLOAD_TOO_LARGE: 'VALIDATION_PAYLOAD_TOO_LARGE',

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // Infrastructure
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT_ERROR: 'TIMEOUT_ERROR',
  CONFIG_MISSING: 'CONFIG_MISSING',
} as const;

export type ErrorClass = typeof ErrorClass[keyof typeof ErrorClass];
