# Stage 1: Install dependencies only when needed
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

ENV NPM_CONFIG_LOGLEVEL=error \
    NPM_CONFIG_FUND=false \
    NPM_CONFIG_AUDIT=false \
    NPM_CONFIG_UPDATE_NOTIFIER=false

COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm (npm ci --legacy-peer-deps --no-fund --no-audit || npm install --legacy-peer-deps --no-fund --no-audit)

# Stage 2: Rebuild the source code only when needed
FROM node:22-alpine AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build arguments for Next.js NEXT_PUBLIC_ variables
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_WS_URL
ARG NEXT_PUBLIC_RAZORPAY_KEY_ID
ARG NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME
ARG NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET
ARG NEXT_PUBLIC_CLOUDINARY_UPLOAD_ASSET_FOLDER
ARG NEXT_PUBLIC_E2E_STAGING

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production
ENV NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY:-ci-placeholder}
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:-ci.firebaseapp.com}
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID:-ci}
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET:-ci.appspot.com}
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID:-"000000000000"}
ENV NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID:-1:000000000000:web:ci}
ENV NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
ENV NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
ENV NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET=${NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET}
ENV NEXT_PUBLIC_CLOUDINARY_UPLOAD_ASSET_FOLDER=${NEXT_PUBLIC_CLOUDINARY_UPLOAD_ASSET_FOLDER}
ENV FIREBASE_CLIENT_EMAIL=ci@ci.iam.gserviceaccount.com
ENV FIREBASE_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nci\n-----END RSA PRIVATE KEY-----"
ENV NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-https://ci.supabase.co}
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY:-ci}
ENV SUPABASE_SERVICE_ROLE_KEY=ci
ENV SIGNING_SECRET_KEY=ci-signing-secret-key-placeholder-32ch
ENV ENCRYPTION_SECRET_KEY=ci-encryption-secret-placeholder-32ch
ENV RECEIPT_SIGNING_SECRET=ci-receipt-signing-secret-placeholder
ENV DOCUMENT_PRIVATE_KEY=ci
ENV DOCUMENT_PUBLIC_KEY=ci
ENV RAZORPAY_KEY_ID=ci
ENV RAZORPAY_KEY_SECRET=ci
ENV RAZORPAY_WEBHOOK_SECRET=ci
ENV CLOUDINARY_API_KEY=ci
ENV CLOUDINARY_API_SECRET=ci
ENV CRON_SECRET=ci
ENV WS_PRIVILEGED_TOKEN=ci-ws-token
ENV NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
ENV NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:3001}
ENV NEXT_PUBLIC_RAZORPAY_KEY_ID=${NEXT_PUBLIC_RAZORPAY_KEY_ID:-ci}
ENV NEXT_PUBLIC_E2E_STAGING=${NEXT_PUBLIC_E2E_STAGING:-false}

RUN --mount=type=cache,target=/app/.next/cache npm run build

# Stage 3: Production runner image
FROM node:22-alpine AS runner
WORKDIR /app

LABEL org.opencontainers.image.title="ITMS Next.js Web App" \
      org.opencontainers.image.description="Intelligent Transportation Management System Frontend & Edge API" \
      org.opencontainers.image.vendor="ADTU Bus Services"

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=5s --start-period=15s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1

CMD ["node", "server.js"]
