"use client";

import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogHeader,DialogTitle } from '@/components/ui/dialog';
import { safeImageSrc } from '@/lib/security/url-sanitizer';
import { motion } from "motion/react";
import {
	Calendar,
	Check,
	CheckCircle,
	Clock,
	Copy,
	CreditCard,
	QrCode,
	Receipt,
	Shield,
	User,
	X
} from 'lucide-react';
import React from 'react';
import { toast } from 'sonner';

interface ReceiptData {
    studentName: string;
    enrollmentId: string;
    paymentMethod: string;
    amount: number;
    sessionValidity: string;
    approvalStatus: string;
    issuedDate: string;
    receiptId: string;
    verifiedAt: string;
    studentProfilePic?: string;
}

interface ReceiptVerificationModalProps {
    isOpen: boolean;
    onClose: () => void;
    receiptData: ReceiptData | null;
    isValid: boolean;
    message?: string;
}

export default function ReceiptVerificationModal({
    isOpen,
    onClose,
    receiptData,
    isValid,
    message
}: ReceiptVerificationModalProps) {
    const [copied, setCopied] = React.useState<string | null>(null);

    const handleCopy = (text: string, label: string) => {
        navigator.clipboard.writeText(text);
        setCopied(label);
        toast.success(`${label} copied!`);
        setTimeout(() => setCopied(null), 2000);
    };

    if (!receiptData && isValid) return null;

    return (
        <Dialog open={isOpen} onOpenChange={(open) => !open && onClose()}>
            <DialogContent className="max-w-[90vw] w-full sm:max-w-[380px] mt-2 p-0 overflow-hidden bg-[#0f111a] border-white/10 shadow-2xl rounded-[24px]">
                <div className="absolute inset-0 opacity-5 pointer-events-none">
                    <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] mix-blend-overlay" />
                </div>

                <DialogHeader className="p-5 pb-0 relative z-10">
                    <div className="flex items-center justify-between mb-1">
                        <div className="flex items-center gap-2">
                            <div className={`p-1.5 rounded-lg ${isValid ? 'bg-emerald-500/10' : 'bg-red-500/10'}`}>
                                <QrCode className={`w-4 h-4 ${isValid ? 'text-emerald-400' : 'text-red-400'}`} />
                            </div>
                            <span className="text-[9px] font-black text-white/40 uppercase tracking-[0.15em]">Verification Result</span>
                        </div>
                    </div>
                    <DialogTitle className="text-xl font-black text-white tracking-tight flex items-center gap-2">
                        {isValid ? (
                            <>
                                <CheckCircle className="w-6 h-6 text-emerald-400" />
                                Receipt Verified
                            </>
                        ) : (
                            <>
                                <X className="w-6 h-6 text-red-500" />
                                Verification Failed
                            </>
                        )}
                    </DialogTitle>
                </DialogHeader>

                <div className="p-5 pt-4 space-y-3 relative z-10">
                    {!isValid ? (
                        <div className="flex flex-col items-center text-center py-6 bg-red-500/5 rounded-[20px] border border-red-500/10">
                            <div className="w-14 h-14 bg-red-500/10 rounded-full flex items-center justify-center mb-4 relative">
                                <Shield className="w-7 h-7 text-red-400" />
                                <motion.div
                                    className="absolute inset-0 rounded-full border-2 border-red-400/30"
                                    animate={{ scale: [1, 1.3, 1], opacity: [0.5, 0, 0.5] }}
                                    transition={{ duration: 2, repeat: Infinity }}
                                />
                            </div>
                            <h3 className="text-lg font-black text-white mb-2">Unable to Verify Authenticity</h3>
                            <p className="text-red-400/80 text-xs px-4 font-medium leading-relaxed mb-3">
                                {message || 'This receipt appears to be modified or not generated by the ADTU Bus Services system.'}
                            </p>
                            <div className="bg-red-500/10 rounded-lg px-4 py-2.5 mx-4 border border-red-500/20">
                                <p className="text-[10px] text-red-300/80 font-semibold leading-relaxed">
                                    Please present the original, system-generated document.
                                    <br />
                                    <span className="text-red-400/60 text-[9px]">Note: Editing this file invalidates its security signature.</span>
                                </p>
                            </div>
                        </div>
                    ) : (
                        receiptData && (
                            <>
                                {/* Student Info Section */}
                                <div className="bg-white/5 rounded-[20px] p-3.5 border border-white/5 hover:bg-white/[0.07] transition-all">
                                    <div className="flex items-start gap-3">
                                        <div className="shrink-0">
                                            {receiptData.studentProfilePic ? (
                                                <div className="w-12 h-12 rounded-full border-2 border-blue-500/20 overflow-hidden shadow-lg">
                                                    <img
                                                        src={safeImageSrc(receiptData.studentProfilePic)}
                                                        alt={receiptData.studentName}
                                                        className="w-full h-full object-cover"
                                                    />
                                                </div>
                                            ) : (
                                                <div className="w-12 h-12 rounded-full bg-gradient-to-br from-blue-500/20 to-indigo-500/20 border-2 border-blue-500/20 flex items-center justify-center shadow-lg">
                                                    <User className="w-5 h-5 text-blue-400" />
                                                </div>
                                            )}
                                        </div>
                                        <div className="flex-1 min-w-0">
                                            <div className="flex items-center justify-between">
                                                <span className="text-[8px] font-black text-white/30 uppercase tracking-widest">Student Information</span>
                                                <button
                                                    onClick={() => handleCopy(receiptData.enrollmentId, 'Enrollment ID')}
                                                    className="p-1 hover:bg-white/5 rounded-md transition-colors"
                                                >
                                                    {copied === 'Enrollment ID' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3 text-white/30" />}
                                                </button>
                                            </div>
                                            <h4 className="text-base font-bold text-white truncate leading-tight mt-0.5">{receiptData.studentName}</h4>
                                            <p className="text-[11px] font-mono text-blue-400/70 font-bold">{receiptData.enrollmentId}</p>
                                        </div>
                                    </div>
                                </div>

                                {/* Details Grid */}
                                <div className="grid grid-cols-2 gap-2.5">
                                    <div className="bg-white/5 rounded-[16px] p-2.5 border border-white/5">
                                        <div className="flex items-center gap-1.5 mb-1">
                                            <CreditCard className="w-3 h-3 text-purple-400" />
                                            <span className="text-[8px] font-black text-white/30 uppercase tracking-widest">Method</span>
                                        </div>
                                        <div className="text-xs font-bold text-white truncate">{receiptData.paymentMethod}</div>
                                    </div>
                                    <div className="bg-emerald-500/5 rounded-[16px] p-2.5 border border-emerald-500/10">
                                        <div className="flex items-center gap-1.5 mb-1">
                                            <Receipt className="w-3 h-3 text-emerald-400" />
                                            <span className="text-[8px] font-black text-emerald-400/40 uppercase tracking-widest">Amount</span>
                                        </div>
                                        <div className="text-sm font-black text-emerald-400">₹{receiptData.amount.toLocaleString('en-IN')}</div>
                                    </div>
                                    <div className="bg-white/5 rounded-[16px] p-2.5 border border-white/5">
                                        <div className="flex items-center gap-1.5 mb-1">
                                            <Calendar className="w-3 h-3 text-amber-400" />
                                            <span className="text-[8px] font-black text-white/30 uppercase tracking-widest">Session</span>
                                        </div>
                                        <div className="text-[11px] font-bold text-white/90">{receiptData.sessionValidity}</div>
                                    </div>
                                    <div className="bg-white/5 rounded-[16px] p-2.5 border border-white/5">
                                        <div className="flex items-center gap-1.5 mb-1">
                                            <Clock className="w-3 h-3 text-cyan-400" />
                                            <span className="text-[8px] font-black text-white/30 uppercase tracking-widest">Issued On</span>
                                        </div>
                                        <div className="text-[11px] font-bold text-white/90 truncate">{receiptData.issuedDate}</div>
                                    </div>
                                </div>

                                {/* Receipt ID - Full Width Dark */}
                                <div className="bg-[#05060a] rounded-[16px] p-3 border border-white/10 text-center relative overflow-hidden group">
                                    <div className="absolute inset-0 bg-white/5 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />
                                    <span className="text-[8px] font-black text-white/30 uppercase tracking-[0.2em] block mb-1">Receipt ID</span>
                                    <div
                                        onClick={() => handleCopy(receiptData.receiptId, 'Receipt ID')}
                                        className="text-xs font-mono font-bold text-white/90 truncate cursor-pointer select-all flex items-center justify-center gap-2"
                                    >
                                        {receiptData.receiptId}
                                        {copied === 'Receipt ID' ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3 text-white/20" />}
                                    </div>
                                </div>

                                {/* Status & Verified Badge Combined */}
                                <div className="bg-emerald-500/10 border border-emerald-500/20 rounded-[16px] p-3 flex items-center justify-between">
                                    <div className="flex flex-col">
                                        <span className="text-[8px] font-black text-emerald-500/60 uppercase tracking-widest mb-0.5">Status</span>
                                        <span className="text-xs font-black text-emerald-400 uppercase">{receiptData.approvalStatus}</span>
                                    </div>
                                    <div className="h-6 w-[1px] bg-emerald-500/20 mx-2"></div>
                                    <div className="text-right">
                                        <div className="flex items-center gap-1.5 justify-end text-emerald-400/50 mb-0.5">
                                            <Shield className="w-3 h-3" />
                                            <span className="text-[7px] font-bold uppercase tracking-wider">Verified At</span>
                                        </div>
                                        <span className="text-[9px] text-emerald-400/80 font-mono font-bold">
                                            {new Date(receiptData.verifiedAt).toLocaleString('en-IN', {
                                                day: 'numeric', month: 'numeric', year: 'numeric',
                                                hour: 'numeric', minute: 'numeric', hour12: true
                                            })}
                                        </span>
                                    </div>
                                </div>

                                {/* Verified By ADTU System Seal */}
                                <motion.div
                                    className="bg-gradient-to-r from-emerald-500/5 to-blue-500/5 border border-emerald-500/20 rounded-[16px] p-3 flex items-center justify-center gap-2 relative overflow-hidden"
                                    initial={{ opacity: 0, scale: 0.95 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    transition={{ delay: 0.3, duration: 0.4 }}
                                >
                                    <motion.div
                                        className="absolute inset-0 bg-emerald-500/5"
                                        animate={{ opacity: [0.3, 0.6, 0.3] }}
                                        transition={{ duration: 2, repeat: Infinity }}
                                    />
                                    <Shield className="w-4 h-4 text-emerald-400" />
                                    <span className="text-[10px] font-black text-emerald-400/80 uppercase tracking-wider relative z-10">
                                        Verified by ADTU Secure System
                                    </span>
                                </motion.div>
                            </>
                        )
                    )}

                    <div className="pt-2">
                        <Button
                            onClick={onClose}
                            className={`w-full py-5 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${isValid
                                ? 'bg-emerald-600 hover:bg-emerald-500 text-white shadow-[0_5px_15px_rgba(16,185,129,0.2)]'
                                : 'bg-red-600 hover:bg-red-500 text-white shadow-[0_5px_15px_rgba(239,68,68,0.2)]'
                                }`}
                        >
                            {isValid ? 'Continue Scanning' : 'Close and Retry'}
                        </Button>
                    </div>
                </div>
            </DialogContent>
        </Dialog>
    );
}
