import { withSecurity } from '@/lib/security/api-security';
import {
	buildDocumentPayloadFromPayment,
	parseSecureQRData,
	verifyReceiptIntegrity,
} from '@/lib/security/document-crypto.service';
import { getModeratorPermissions } from '@/lib/security/moderator-permissions';
import { RateLimits } from '@/lib/security/rate-limiter';
import { quickValidateReceiptToken,verifyReceiptSignature } from '@/lib/security/receipt-security.service';
import { VerifyReceiptSchema } from '@/lib/security/validation-schemas';
import { paymentsSupabaseService } from '@/lib/services/payments-supabase';
import { NextResponse } from 'next/server';

type VerifyReceiptBody = {
  receiptToken: string;
  scanContext?: {
    busId?: string;
    routeId?: string;
    source?: string;
    [key: string]: unknown;
  };
};

function invalidReceipt(
  status: string,
  message: string,
  options: { suspicious?: boolean; httpStatus?: number } = {}
) {
  return NextResponse.json(
    {
      valid: false,
      status,
      message,
      suspicious: options.suspicious || false,
    },
    { status: options.httpStatus || 200 }
  );
}

function formatDate(value?: string | Date | null): string {
  if (!value) return 'N/A';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return 'N/A';
  return date.toLocaleDateString('en-IN', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
}

async function canVerifyPaymentReceipt(role: string, uid: string): Promise<boolean> {
  if (role === 'admin') return true;
  if (role !== 'moderator') return false;

  const permissions = await getModeratorPermissions(uid);
  return Boolean(
    permissions.payments.canApproveOfflinePayment
    || permissions.payments.canRejectOfflinePayment
  );
}

export const POST = withSecurity<VerifyReceiptBody>(
  async (_request, { auth, body }) => {
    if (!(await canVerifyPaymentReceipt(auth.role, auth.uid))) {
      return NextResponse.json(
        { valid: false, status: 'forbidden', message: 'Payment receipt verification permission is required.' },
        { status: 403 }
      );
    }

    const receiptToken = body.receiptToken.trim();
    const isV2Token = receiptToken.startsWith('ADTU-R2-');
    const isV1Token = receiptToken.startsWith('ADTU-R1-');

    if (!isV2Token && !isV1Token) {
      return invalidReceipt(
        'invalid',
        'Unrecognized receipt format. Please show a valid ADTU receipt.',
        { suspicious: true }
      );
    }

    let receiptId = '';
    let truncatedSignature: string | undefined;
    let legacyPayload: ReturnType<typeof verifyReceiptSignature> = null;

    if (isV2Token) {
      const qrData = parseSecureQRData(receiptToken);
      if (!qrData) {
        return invalidReceipt(
          'tampered',
          'Unable to verify document authenticity. This receipt appears to be modified or not generated by the ADTU Bus Services system. Please present the original, system-generated document.',
          { suspicious: true }
        );
      }

      receiptId = qrData.rid;
      truncatedSignature = qrData.sig;
    } else {
      if (!quickValidateReceiptToken(receiptToken)) {
        return invalidReceipt(
          'tampered',
          'Unable to verify document authenticity. This receipt appears to be modified or not generated by the ADTU Bus Services system. Please present the original, system-generated document.',
          { suspicious: true }
        );
      }

      legacyPayload = verifyReceiptSignature(receiptToken);
      if (!legacyPayload) {
        return invalidReceipt(
          'expired',
          'Receipt verification has expired or is invalid.'
        );
      }

      receiptId = legacyPayload.receiptId;
    }

    const payment = await paymentsSupabaseService.getPaymentById(receiptId);
    if (!payment) {
      return invalidReceipt(
        'not_found',
        'Receipt not found in system records.',
        { suspicious: true }
      );
    }

    if (payment.status !== 'Completed') {
      return invalidReceipt(
        'invalid',
        'Receipt is not valid because the payment is not approved.',
        { suspicious: payment.status === 'Rejected' }
      );
    }

    if (isV2Token) {
      if (!payment.document_signature || !truncatedSignature) {
        return invalidReceipt(
          'signature_mismatch',
          'This receipt cannot be cryptographically verified. Please regenerate the official receipt from the student dashboard.',
          { suspicious: true }
        );
      }

      const documentPayload = buildDocumentPayloadFromPayment(payment);
      const integrityResult = verifyReceiptIntegrity(
        documentPayload,
        payment.document_signature,
        truncatedSignature
      );

      if (!integrityResult.valid) {
        console.warn('[ReceiptVerify] Receipt integrity failure:', {
          receiptId,
          status: integrityResult.status,
        });

        return invalidReceipt(
          integrityResult.status,
          integrityResult.message,
          { suspicious: integrityResult.suspicious }
        );
      }
    }

    if (legacyPayload) {
      const uidMatches = !legacyPayload.studentUid || payment.student_uid === legacyPayload.studentUid;
      const amountMatches = !legacyPayload.amount || Number(payment.amount || 0) === Number(legacyPayload.amount);

      if (!uidMatches || !amountMatches) {
        return invalidReceipt(
          'tampered',
          'Unable to verify document authenticity. Data mismatch detected.',
          { suspicious: true }
        );
      }
    }

    const baseReceiptData = {
      studentName: payment.student_name || 'Student',
      enrollmentId: payment.student_id || 'N/A',
      paymentMethod: payment.method || 'Offline',
      amount: payment.amount || 0,
      sessionValidity: `${payment.session_start_year || 'N/A'} - ${payment.session_end_year || 'N/A'}`,
      approvalStatus: 'Approved',
      issuedDate: formatDate(payment.transaction_date || payment.created_at),
      receiptId: payment.payment_id,
      verifiedAt: new Date().toISOString(),
      studentUid: payment.student_uid,
      studentProfilePic: '',
    };

    const receiptData = {
        ...baseReceiptData,
        purpose: payment.purpose,
        approvedBy: payment.approved_by,
        razorpayOrderId: payment.razorpay_order_id,
        offlineTransactionId: payment.offline_transaction_id,
        validUntil: formatDate(payment.valid_until),
        metadata: payment.metadata,
        createdAt: payment.created_at,
        updatedAt: payment.transaction_date || payment.created_at,
      };

    return NextResponse.json({
      valid: true,
      status: 'valid',
      message: isV2Token
        ? 'Document authenticity verified. This receipt is genuine and has not been modified.'
        : 'Receipt verified successfully.',
      receiptData,
      tokenInfo: {
        version: isV2Token ? 2 : 1,
        signatureType: isV2Token ? 'RSA-2048' : 'HMAC-SHA256',
      },
      scannerRole: auth.role,
      verifiedAt: new Date().toISOString(),
    });
  },
  {
    requiredRoles: ['admin', 'moderator'],
    schema: VerifyReceiptSchema,
    rateLimit: RateLimits.BUS_PASS_VERIFY,
    allowBodyToken: true,
  }
);
